function [dur, dens] =  GetSpinChara(detvec, fs, len)
% Function: Get spindle characteristics, i.e. duration (sec), density (spindles per minute), 
% onset difference (compared to ground truth). But onset difference is
% calculated by the function of 'get_event_eval.m'. Here we only calculate
% duration and density of detected spindles.

% Input: detvec: detection vector generated by algorithms
%        fs: sampling frequency
%        len: total time length of processed EEG (not only N2 EEG)
if nargin == 2
    total_time = length(detvec)/fs; % in seconds
else
    total_time = len/fs;
end

% Get the beginning and end points of all detection windows
begin_det = find(diff([0;detvec])==1);
stop_det = find(diff([detvec;0])==-1);
dur = (stop_det - begin_det)/fs; % durations in seconds

dens = length(dur)/(total_time/60); % density: spindles per minute;

end